/** @type {import('cz-git').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      ['feat', 'fix', 'docs', 'style', 'refactor', 'perf', 'test', 'build', 'ci', 'chore', 'revert', 'wip'],
    ],
    'subject-case': [0],
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
    'header-max-length': [2, 'always', 100],
  },
  prompt: {
    alias: { fd: 'docs: fix typos' },
    messages: {
          "type": "Select the type of change you are committing:",
          "scope": "Denote the SCOPE of this change (optional):",
          "customScope": "Denote the SCOPE of this change:",
          "subject": "Write a SHORT, IMPERATIVE description of the change:\n",
          "body": "Provide a LONGER description (optional). Use \"|\" for line breaks:\n",
          "breaking": "List any BREAKING CHANGES (optional):\n",
          "footerPrefixesSelect": "Select the ISSUES type of changeList by this change (optional):",
          "customFooterPrefix": "Input ISSUES prefix:",
          "footer": "List any ISSUES by this change. E.g.: #31, #34:\n",
          "generatingByAI": "Generating your AI commit subject...",
          "generatedSelectByAI": "Select suitable subject by AI generated:",
          "confirmCommit": "Are you sure you want to proceed with the commit above?"
    },
    types: [
      { value: 'feat', name: "feat:     ✨  A new feature", emoji: ':sparkles:' },
      { value: 'fix', name: "fix:      🐛  A bug fix", emoji: ':bug:' },
      { value: 'docs', name: "docs:     📝  Documentation only changes", emoji: ':memo:' },
      { value: 'style', name: "style:    🎨  Code style / formatting", emoji: ':art:' },
      { value: 'refactor', name: "refactor: ♻️   Code refactoring", emoji: ':recycle:' },
      { value: 'perf', name: "perf:     ⚡️  Performance improvements", emoji: ':zap:' },
      { value: 'test', name: "test:     ✅  Adding or updating tests", emoji: ':white_check_mark:' },
      { value: 'build', name: "build:    📦️  Build system or dependency changes", emoji: ':package:' },
      { value: 'ci', name: "ci:       🎡  CI configuration changes", emoji: ':ferris_wheel:' },
      { value: 'chore', name: "chore:    🔨  Other changes (no src or test files)", emoji: ':hammer:' },
      { value: 'revert', name: "revert:   ⏪️  Revert a previous commit", emoji: ':rewind:' },
      { value: 'wip', name: "wip:      🚧  Work in progress", emoji: ':construction:' }
    ],
    useEmoji: true,
    emojiAlign: 'center',
    useAI: false,
    aiNumber: 1,
    themeColorCode: '',
    scopes: [],
    allowCustomScopes: true,
    allowEmptyScopes: true,
    customScopesAlign: 'bottom',
    customScopesAlias: 'custom',
    emptyScopesAlias: 'empty',
    upperCaseSubject: false,
    markBreakingChangeMode: false,
    allowBreakingChanges: ['feat', 'fix'],
    breaklineNumber: 100,
    breaklineChar: '|',
    skipQuestions: [],
    issuePrefixes: [
      {"value":"closed","name":"closed:   ISSUES has been processed"},
    ],
    customIssuePrefixAlign: 'top',
    emptyIssuePrefixAlias: 'skip',
    customIssuePrefixAlias: 'custom',
    allowCustomIssuePrefix: true,
    allowEmptyIssuePrefix: true,
    confirmColorize: true,
    maxHeaderLength: Infinity,
    maxSubjectLength: Infinity,
    minSubjectLength: 0,
    scopeOverrides: undefined,
    defaultBody: '',
    defaultIssues: '',
    defaultScope: '',
    defaultSubject: '',
  },
};
